import {safeUrl,taskStats,filterTasks,validateBackup,updateEntry} from './model.js';
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=new Date();const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
let state={programs:[],tasks:[],resources:[]},view='overview',filter='',editing='',editingId='',taskStatus='all',taskProgram='';
try{const saved=JSON.parse(localStorage.getItem('niq-hub-v1'));if(saved)state=validateBackup(saved);}catch{$('#notice').textContent='Saved data could not be loaded. You can continue in this session.';}
function save(){try{localStorage.setItem('niq-hub-v1',JSON.stringify(state));}catch{$('#notice').textContent='Browser storage is unavailable. Changes will only last for this session.';}}
$('#today').textContent=now.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});
const titles={overview:['Your day, in focus.','A clear view of your programs, priorities, and resources.'],programs:['Programs','Track the work that moves your organization forward.'],tasks:['Daily tasks','Turn today’s priorities into progress.'],resources:['Resource library','The links and references you need, all in one place.']};
function empty(label){return `<div class="empty"><div class="empty-icon">＋</div><h3>No ${label} yet</h3><p>Add your first entry to make this workspace your own.</p></div>`;}
function list(type,items){if(!items.length)return empty(type);return `<div class="entries">${items.map(x=>`<article class="entry">${type==='tasks'?`<input type="checkbox" aria-label="Complete ${escape(x.title)}" data-toggle="${escape(x.id)}" ${x.done?'checked':''}>`:''}<div class="entry-body"><h3 class="${x.done?'completed':''}">${type==='resources'&&safeUrl(x.url)?`<a href="${escape(safeUrl(x.url))}" target="_blank" rel="noopener noreferrer">${escape(x.title)} ↗</a>`:escape(x.title)}</h3><p>${escape(type==='programs'?x.description:type==='tasks'?[x.owner,x.due,x.program].filter(Boolean).join(' · '):x.category)}</p></div>${type==='programs'?`<span class="badge">${escape(x.status)}</span>`:''}<button class="edit" data-edit="${escape(x.id)}" data-type="${type}" aria-label="Edit ${escape(x.title)}">Edit</button><button class="delete" data-delete="${escape(x.id)}" data-type="${type}" aria-label="Delete ${escape(x.title)}">×</button></article>`).join('')}</div>`;}
function render(){const stats=taskStats(state.tasks,today);$('#heading').textContent=titles[view][0];$('#subtitle').textContent=titles[view][1];document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
if(view==='overview'){$('#content').innerHTML=`<div class="stats"><article><p>Active programs</p><strong>${state.programs.filter(p=>p.status!=='Completed').length}</strong><span>Moving forward</span></article><article><p>Open tasks</p><strong>${stats.open}</strong><span>${stats.overdue} overdue</span></article><article><p>Completed tasks</p><strong>${stats.completed}</strong><span>Progress you can see</span></article><article><p>Saved resources</p><strong>${state.resources.length}</strong><span>Ready when you need them</span></article></div><div class="overview-grid"><section class="panel"><div class="section-head"><div><span class="eyebrow">NEXT UP</span><h2>Your priorities</h2></div><button class="primary" data-add="tasks">+ Add task</button></div>${list('tasks',state.tasks.filter(t=>!t.done).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,5))}</section><section class="panel"><div class="section-head"><div><span class="eyebrow">AT A GLANCE</span><h2>Programs</h2></div><button data-add="programs">+ Add</button></div>${list('programs',state.programs.slice(0,4))}</section></div><section class="panel library"><div class="section-head"><div><span class="eyebrow">QUICK ACCESS</span><h2>Resource library</h2></div><button data-add="resources">+ Add resource</button></div>${list('resources',state.resources.slice(0,3))}</section>`;
}else{$('#content').innerHTML=`<section class="panel"><div class="section-head"><input id="search" type="search" aria-label="Search ${view}" placeholder="Search ${view}…" value="${escape(filter)}"><button class="primary" data-add="${view}">+ Add ${view==='resources'?'resource':view==='programs'?'program':'task'}</button></div>${view==='tasks'?taskFilters():''}${list(view,view==='tasks'?filterTasks(state.tasks,{status:taskStatus,program:taskProgram,query:filter},today):state[view].filter(x=>Object.values(x).some(v=>String(v).toLowerCase().includes(filter.toLowerCase()))))}</section>`;}}
const field=(name,label,type='text',required=false)=>`<label>${label}<input name="${name}" type="${type}" ${required?'required':''} maxlength="500"></label>`;
function open(type,id=''){editing=type;editingId=id;$('#dialog-title').textContent=(id?'Edit ':'Add ')+({tasks:'task',programs:'program',resources:'resource'}[type]);$('#fields').innerHTML=field('title','Title','text',true)+(type==='programs'?`${field('description','Description')}<label>Status<select name="status"><option>Planning</option><option>In progress</option><option>On hold</option><option>Completed</option></select></label>`:type==='tasks'?`${field('owner','Owner')}${field('due','Due date','date')}<label>Program<select name="program"><option value="">Unassigned</option>${state.programs.map(p=>`<option>${escape(p.title)}</option>`).join('')}</select></label>`:`${field('url','Resource URL','url',true)}${field('category','Category')}`);const item=state[type].find(x=>x.id===id);if(item){for(const [key,value] of Object.entries(item)){const control=$('#entry-form').elements[key];if(control){if(key==='program'&&value&&!Array.from(control.options).some(o=>o.value===value))control.add(new Option(value,value));control.value=value;}}}$('#editor').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;filter='';render();}if(b.dataset.add)open(b.dataset.add);if(b.dataset.edit)open(b.dataset.type,b.dataset.edit);if(b.dataset.delete&&confirm('Delete this entry?')){const removed=state[b.dataset.type].find(x=>x.id===b.dataset.delete);state[b.dataset.type]=state[b.dataset.type].filter(x=>x.id!==b.dataset.delete);if(b.dataset.type==='programs')state.tasks=state.tasks.map(t=>t.program===removed.title?{...t,program:''}:t);save();render();}});
document.addEventListener('change',e=>{if(e.target.id==='task-status'){taskStatus=e.target.value;render();}if(e.target.id==='task-program'){taskProgram=e.target.value;render();}if(e.target.dataset.toggle){const task=state.tasks.find(t=>t.id===e.target.dataset.toggle);if(task){task.done=e.target.checked;save();render();}}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const cursor=e.target.selectionStart;filter=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(cursor,cursor);}});
$('#entry-form').addEventListener('submit',e=>{e.preventDefault();const item=Object.fromEntries(new FormData(e.target));item.title=item.title.trim();if(!item.title){e.target.elements.title.setCustomValidity('Enter a title.');e.target.elements.title.reportValidity();return;}if(editing==='resources'&&!safeUrl(item.url)){e.target.elements.url.setCustomValidity('Use an http or https URL.');e.target.elements.url.reportValidity();return;}item.id=editingId||crypto.randomUUID();if(editing==='tasks')item.done=state.tasks.find(t=>t.id===editingId)?.done??false;state=updateEntry(state,editing,item);save();$('#editor').close();render();});
$('#entry-form').addEventListener('input',e=>e.target.setCustomValidity?.(''));
$('#close-dialog').onclick=$('#cancel').onclick=()=>$('#editor').close();render();

function taskFilters(){return `<div class="task-filters"><label>Status<select id="task-status">${[['all','All tasks'],['open','Open'],['completed','Completed'],['today','Due today'],['overdue','Overdue']].map(([v,label])=>`<option value="${v}" ${taskStatus===v?'selected':''}>${label}</option>`).join('')}</select></label><label>Program<select id="task-program"><option value="">All programs</option>${[...new Set(state.tasks.map(t=>t.program).filter(Boolean))].map(p=>`<option value="${escape(p)}" ${taskProgram===p?'selected':''}>${escape(p)}</option>`).join('')}</select></label></div>`;}
$('#export-data').onclick=()=>{
 const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),data:state},null,2)],{type:'application/json'});
 const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`niq-hub-${today}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 $('#notice').textContent='Backup exported. Keep it somewhere safe.';
};
$('#import-data').onclick=()=>$('#backup-file').click();
$('#backup-file').addEventListener('change',async e=>{
 const file=e.target.files[0];if(!file)return;
 try{
  if(file.size>10*1024*1024)throw new Error('Choose a backup smaller than 10 MB.');
  const restored=validateBackup(JSON.parse(await file.text()));
  const count=Object.values(restored).reduce((n,rows)=>n+rows.length,0);
  if(!confirm(`Replace this workspace with ${count} entries from the backup? Export your current data first if you want to keep it.`))return;
  // Persist before replacing the current state so a storage failure leaves it intact.
  localStorage.setItem('niq-hub-v1',JSON.stringify(restored));state=restored;filter='';taskStatus='all';taskProgram='';render();$('#notice').textContent=`Imported ${count} entries.`;
 }catch(error){$('#notice').textContent=`Import failed. Your current data is unchanged. ${error.message}`;}
 finally{e.target.value='';}
});
